API changes and improvements
psteinb/c2st pull request #12
Opened 2022-05-03 09:12 UTC by elcorto

* API: Remove `c2st_()`, add `return_scores` kwd to `c2st()` instead
* API: Support passing `cv` and `clf` class instances, remove `clf_class` and
  `clf_kwargs`, retain previous defaults but now allow all classifiers and CV
  splitters with sklearn API to be passed
* ENH: Add more examples to README
* ENH: Add optional NaN handling
* ENH: Fix all typing issues, add `mypy.ini`
* ENH: Add API-only tests
* BEH: Use ubuntu-latest

2022-05-03 09:25 UTC, psteinb requested changes

2022-05-03 09:25 UTC, psteinb commented on README.md
> +# now shift the mean of Y a bit
```suggestion
# now shift the mean of Y by `0.3`
```

2022-05-03 09:25 UTC, psteinb commented on README.md
> +# now shift the mean of Y a bit
Let's be precise and help people not familiar with the `np.random` API to understand the example.

2022-05-03 09:25 UTC, psteinb commented on README.md
> +# and some more
```suggestion
# let's move Y more extensively away from X to `1.5`
```

2022-05-03 09:25 UTC, psteinb commented on README.md
> +# or change the distribution's width
```suggestion
# or change the distribution's variance, so we compare a narrow to a wide distribution at the same loc
```

2022-05-04 20:48 UTC, elcorto commented
I added the suggested README changes. @psteinb is there anything else to be done?

2022-05-05 08:03 UTC, psteinb approved these changes
LGTM!

2022-05-05 08:04 UTC, merged

2022-05-05 08:04 UTC, psteinb commented
This is such a great addition. Thanks.